# -*- coding: utf-8 -*-
"""Copy of Python _2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EsQ2zGlu-ciagpCfUK_MKsdFLdkhzsRG
"""

print('UMIT')

